dist: trusty

language: python
python:
  - "3.5"

install:
- pip install screed==0.9
- pip install pytest
- git clone https://github.com/dib-lab/literate-resting.git
- git clone https://github.com/dib-lab/khmer.git -b v2.0
- cd khmer && make all; cd ..

script:
- cd 001-extract-reads-by-coverage
- ../literate-resting/scan.py index.rst
- ./index.rst.sh
